repository_type: pipeline

nf_core_version: 3.3.1

lint: {}

template:
  org: nf-core
  name: hadge
  description: Comprehensive pipeline for donor demultiplexing in single cell
  author: Fabiola Curion
  version: 1.0.0dev
  force: true
  outdir: .
  skip_features: [
    "fastqc"
  ]
  is_nfcore: true
