lint:
  files_unchanged:
    - .github/PULL_REQUEST_TEMPLATE.md
nf_core_version: 4.0.0
repository_type: pipeline
template:
  author: Fabiola Curion
  description: Comprehensive pipeline for donor demultiplexing in single cell
  force: false
  is_nfcore: true
  name: hadge
  org: nf-core
  outdir: .
  skip_features:
    - fastqc
  version: 1.0.0dev
