lint: {}
nf_core_version: 3.3.1
repository_type: pipeline
template:
  author: Fabiola Curion
  version: 1.0.0dev
  force: true
  outdir: .
  skip_features: [
    "fastqc"
  ]
  is_nfcore: true
  name: hadge
  org: nf-core
