channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::pegasusio=0.10.0
  - conda-forge::anndata=0.11.4
  - conda-forge::mudata=0.3.1
  - conda-forge::numpy=1.24.2
  - conda-forge::pandas=2.3.1
  - conda-forge::pathlib=1.0.1
  - conda-forge::scanpy=1.11.2
