contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #hadge channel"
    url: https://nfcore.slack.com/channels/hadge
    about: Discussion about the nf-core/hadge pipeline
